services:

  mysql_db:
    image: 'mysql:latest'
    container_name: mysql_db
    restart: always
    env_file: ./.env
    ports:
      - ${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      retries: 10
      interval: 3s
      timeout: 30s

  redis_cache:
    image: redis:latest
    container_name: redis
    ports:
      - ${REDIS_LOCAL_PORT}:${REDIS_DOCKER_PORT}
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  app:
    container_name: app
    depends_on:
      mysql_db:
        condition: service_healthy
      redis_cache:
        condition: service_healthy
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - ${SPRING_APP_LOCAL_PORT}:${SPRING_APP_DOCKER_PORT}
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:${MYSQL_DOCKER_PORT}/${MYSQL_DATABASE}
      SPRING_PROFILES_ACTIVE: docker

volumes:
  mysql-data:

networks:
  app-network: