CREATE TABLE IF NOT EXISTS GAME
(
    ID            BIGSERIAL    PRIMARY KEY,
    TIMESTAMP     TIMESTAMP(6) NOT NULL,
    COMPUTER_MOVE VARCHAR(255) NOT NULL,
    RESULT        VARCHAR(255) NOT NULL,
    STATUS        VARCHAR(255) NOT NULL,
    USER_MOVE     VARCHAR(255) NOT NULL
);